name: Test

on:
  workflow_dispatch:
  push:
    #  branches: [ master ]
  pull_request:
    #  branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-latest, 
          macos-latest,
          windows-latest,
        ]  
        go-version: ['1.20', '1.21', '1.22', '1.23']
        # See supported Go release schedule at https://golang.org/doc/devel/release.html
        # https://github.com/actions/go-versions/blob/main/versions-manifest.json
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
